### YamlMime:ManagedReference
items:
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
  commentId: T:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
  id: BufferConfigurationBuilder
  parent: Orleans.GpuBridge.Logging.Core
  children:
  - Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.DropOnFull(System.Boolean)
  - Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithCapacity(System.Int32)
  - Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithFlushInterval(System.TimeSpan)
  - Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithMaxBatchSize(System.Int32)
  langs:
  - csharp
  - vb
  name: BufferConfigurationBuilder
  nameWithType: BufferConfigurationBuilder
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
  type: Class
  source:
    remote:
      path: src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
      branch: main
      repo: https://github.com/mivertowski/Orleans.GpuBridge.Core.git
    id: BufferConfigurationBuilder
    path: ../src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
    startLine: 5
  assemblies:
  - Orleans.GpuBridge.Logging
  namespace: Orleans.GpuBridge.Logging.Core
  summary: Builder for configuring buffer settings.
  example: []
  syntax:
    content: public sealed class BufferConfigurationBuilder
    content.vb: Public NotInheritable Class BufferConfigurationBuilder
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithCapacity(System.Int32)
  commentId: M:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithCapacity(System.Int32)
  id: WithCapacity(System.Int32)
  parent: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
  langs:
  - csharp
  - vb
  name: WithCapacity(int)
  nameWithType: BufferConfigurationBuilder.WithCapacity(int)
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithCapacity(int)
  type: Method
  source:
    remote:
      path: src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
      branch: main
      repo: https://github.com/mivertowski/Orleans.GpuBridge.Core.git
    id: WithCapacity
    path: ../src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
    startLine: 14
  assemblies:
  - Orleans.GpuBridge.Logging
  namespace: Orleans.GpuBridge.Logging.Core
  syntax:
    content: public BufferConfigurationBuilder WithCapacity(int capacity)
    parameters:
    - id: capacity
      type: System.Int32
    return:
      type: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
    content.vb: Public Function WithCapacity(capacity As Integer) As BufferConfigurationBuilder
  overload: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithCapacity*
  nameWithType.vb: BufferConfigurationBuilder.WithCapacity(Integer)
  fullName.vb: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithCapacity(Integer)
  name.vb: WithCapacity(Integer)
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithMaxBatchSize(System.Int32)
  commentId: M:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithMaxBatchSize(System.Int32)
  id: WithMaxBatchSize(System.Int32)
  parent: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
  langs:
  - csharp
  - vb
  name: WithMaxBatchSize(int)
  nameWithType: BufferConfigurationBuilder.WithMaxBatchSize(int)
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithMaxBatchSize(int)
  type: Method
  source:
    remote:
      path: src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
      branch: main
      repo: https://github.com/mivertowski/Orleans.GpuBridge.Core.git
    id: WithMaxBatchSize
    path: ../src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
    startLine: 20
  assemblies:
  - Orleans.GpuBridge.Logging
  namespace: Orleans.GpuBridge.Logging.Core
  syntax:
    content: public BufferConfigurationBuilder WithMaxBatchSize(int batchSize)
    parameters:
    - id: batchSize
      type: System.Int32
    return:
      type: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
    content.vb: Public Function WithMaxBatchSize(batchSize As Integer) As BufferConfigurationBuilder
  overload: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithMaxBatchSize*
  nameWithType.vb: BufferConfigurationBuilder.WithMaxBatchSize(Integer)
  fullName.vb: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithMaxBatchSize(Integer)
  name.vb: WithMaxBatchSize(Integer)
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithFlushInterval(System.TimeSpan)
  commentId: M:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithFlushInterval(System.TimeSpan)
  id: WithFlushInterval(System.TimeSpan)
  parent: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
  langs:
  - csharp
  - vb
  name: WithFlushInterval(TimeSpan)
  nameWithType: BufferConfigurationBuilder.WithFlushInterval(TimeSpan)
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithFlushInterval(System.TimeSpan)
  type: Method
  source:
    remote:
      path: src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
      branch: main
      repo: https://github.com/mivertowski/Orleans.GpuBridge.Core.git
    id: WithFlushInterval
    path: ../src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
    startLine: 26
  assemblies:
  - Orleans.GpuBridge.Logging
  namespace: Orleans.GpuBridge.Logging.Core
  syntax:
    content: public BufferConfigurationBuilder WithFlushInterval(TimeSpan interval)
    parameters:
    - id: interval
      type: System.TimeSpan
    return:
      type: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
    content.vb: Public Function WithFlushInterval(interval As TimeSpan) As BufferConfigurationBuilder
  overload: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithFlushInterval*
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.DropOnFull(System.Boolean)
  commentId: M:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.DropOnFull(System.Boolean)
  id: DropOnFull(System.Boolean)
  parent: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
  langs:
  - csharp
  - vb
  name: DropOnFull(bool)
  nameWithType: BufferConfigurationBuilder.DropOnFull(bool)
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.DropOnFull(bool)
  type: Method
  source:
    remote:
      path: src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
      branch: main
      repo: https://github.com/mivertowski/Orleans.GpuBridge.Core.git
    id: DropOnFull
    path: ../src/Orleans.GpuBridge.Logging/Core/Builders/BufferConfigurationBuilder.cs
    startLine: 32
  assemblies:
  - Orleans.GpuBridge.Logging
  namespace: Orleans.GpuBridge.Logging.Core
  syntax:
    content: public BufferConfigurationBuilder DropOnFull(bool drop = true)
    parameters:
    - id: drop
      type: System.Boolean
    return:
      type: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
    content.vb: Public Function DropOnFull(drop As Boolean = True) As BufferConfigurationBuilder
  overload: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.DropOnFull*
  nameWithType.vb: BufferConfigurationBuilder.DropOnFull(Boolean)
  fullName.vb: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.DropOnFull(Boolean)
  name.vb: DropOnFull(Boolean)
references:
- uid: Orleans.GpuBridge.Logging.Core
  commentId: N:Orleans.GpuBridge.Logging.Core
  href: Orleans.html
  name: Orleans.GpuBridge.Logging.Core
  nameWithType: Orleans.GpuBridge.Logging.Core
  fullName: Orleans.GpuBridge.Logging.Core
  spec.csharp:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.Logging
    name: Logging
    href: Orleans.GpuBridge.Logging.html
  - name: .
  - uid: Orleans.GpuBridge.Logging.Core
    name: Core
    href: Orleans.GpuBridge.Logging.Core.html
  spec.vb:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.Logging
    name: Logging
    href: Orleans.GpuBridge.Logging.html
  - name: .
  - uid: Orleans.GpuBridge.Logging.Core
    name: Core
    href: Orleans.GpuBridge.Logging.Core.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithCapacity*
  commentId: Overload:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithCapacity
  href: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.html#Orleans_GpuBridge_Logging_Core_BufferConfigurationBuilder_WithCapacity_System_Int32_
  name: WithCapacity
  nameWithType: BufferConfigurationBuilder.WithCapacity
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithCapacity
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
  commentId: T:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
  parent: Orleans.GpuBridge.Logging.Core
  href: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.html
  name: BufferConfigurationBuilder
  nameWithType: BufferConfigurationBuilder
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithMaxBatchSize*
  commentId: Overload:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithMaxBatchSize
  href: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.html#Orleans_GpuBridge_Logging_Core_BufferConfigurationBuilder_WithMaxBatchSize_System_Int32_
  name: WithMaxBatchSize
  nameWithType: BufferConfigurationBuilder.WithMaxBatchSize
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithMaxBatchSize
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithFlushInterval*
  commentId: Overload:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithFlushInterval
  href: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.html#Orleans_GpuBridge_Logging_Core_BufferConfigurationBuilder_WithFlushInterval_System_TimeSpan_
  name: WithFlushInterval
  nameWithType: BufferConfigurationBuilder.WithFlushInterval
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.WithFlushInterval
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.timespan
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.DropOnFull*
  commentId: Overload:Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.DropOnFull
  href: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.html#Orleans_GpuBridge_Logging_Core_BufferConfigurationBuilder_DropOnFull_System_Boolean_
  name: DropOnFull
  nameWithType: BufferConfigurationBuilder.DropOnFull
  fullName: Orleans.GpuBridge.Logging.Core.BufferConfigurationBuilder.DropOnFull
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
