### YamlMime:ManagedReference
items:
- uid: Orleans.GpuBridge.Grains.Stream.Configuration
  commentId: N:Orleans.GpuBridge.Grains.Stream.Configuration
  id: Orleans.GpuBridge.Grains.Stream.Configuration
  children:
  - Orleans.GpuBridge.Grains.Stream.Configuration.BackpressureConfig
  - Orleans.GpuBridge.Grains.Stream.Configuration.BatchAccumulationConfig
  - Orleans.GpuBridge.Grains.Stream.Configuration.StreamProcessingConfiguration
  langs:
  - csharp
  - vb
  name: Orleans.GpuBridge.Grains.Stream.Configuration
  nameWithType: Orleans.GpuBridge.Grains.Stream.Configuration
  fullName: Orleans.GpuBridge.Grains.Stream.Configuration
  type: Namespace
  assemblies:
  - Orleans.GpuBridge.Grains
references:
- uid: Orleans.GpuBridge.Grains.Stream.Configuration.BackpressureConfig
  commentId: T:Orleans.GpuBridge.Grains.Stream.Configuration.BackpressureConfig
  parent: Orleans.GpuBridge.Grains.Stream.Configuration
  href: Orleans.GpuBridge.Grains.Stream.Configuration.BackpressureConfig.html
  name: BackpressureConfig
  nameWithType: BackpressureConfig
  fullName: Orleans.GpuBridge.Grains.Stream.Configuration.BackpressureConfig
- uid: Orleans.GpuBridge.Grains.Stream.Configuration.BatchAccumulationConfig
  commentId: T:Orleans.GpuBridge.Grains.Stream.Configuration.BatchAccumulationConfig
  parent: Orleans.GpuBridge.Grains.Stream.Configuration
  href: Orleans.GpuBridge.Grains.Stream.Configuration.BatchAccumulationConfig.html
  name: BatchAccumulationConfig
  nameWithType: BatchAccumulationConfig
  fullName: Orleans.GpuBridge.Grains.Stream.Configuration.BatchAccumulationConfig
- uid: Orleans.GpuBridge.Grains.Stream.Configuration.StreamProcessingConfiguration
  commentId: T:Orleans.GpuBridge.Grains.Stream.Configuration.StreamProcessingConfiguration
  parent: Orleans.GpuBridge.Grains.Stream.Configuration
  href: Orleans.GpuBridge.Grains.Stream.Configuration.StreamProcessingConfiguration.html
  name: StreamProcessingConfiguration
  nameWithType: StreamProcessingConfiguration
  fullName: Orleans.GpuBridge.Grains.Stream.Configuration.StreamProcessingConfiguration
- uid: Orleans.GpuBridge.Grains.Stream.Configuration
  commentId: N:Orleans.GpuBridge.Grains.Stream.Configuration
  href: Orleans.html
  name: Orleans.GpuBridge.Grains.Stream.Configuration
  nameWithType: Orleans.GpuBridge.Grains.Stream.Configuration
  fullName: Orleans.GpuBridge.Grains.Stream.Configuration
  spec.csharp:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.Grains
    name: Grains
    href: Orleans.GpuBridge.Grains.html
  - name: .
  - uid: Orleans.GpuBridge.Grains.Stream
    name: Stream
    href: Orleans.GpuBridge.Grains.Stream.html
  - name: .
  - uid: Orleans.GpuBridge.Grains.Stream.Configuration
    name: Configuration
    href: Orleans.GpuBridge.Grains.Stream.Configuration.html
  spec.vb:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.Grains
    name: Grains
    href: Orleans.GpuBridge.Grains.html
  - name: .
  - uid: Orleans.GpuBridge.Grains.Stream
    name: Stream
    href: Orleans.GpuBridge.Grains.Stream.html
  - name: .
  - uid: Orleans.GpuBridge.Grains.Stream.Configuration
    name: Configuration
    href: Orleans.GpuBridge.Grains.Stream.Configuration.html
