### YamlMime:ManagedReference
items:
- uid: Orleans.GpuBridge.Runtime.Configuration
  commentId: N:Orleans.GpuBridge.Runtime.Configuration
  id: Orleans.GpuBridge.Runtime.Configuration
  children:
  - Orleans.GpuBridge.Runtime.Configuration.ProviderSelectionOptions
  - Orleans.GpuBridge.Runtime.Configuration.RequiredCapabilities
  langs:
  - csharp
  - vb
  name: Orleans.GpuBridge.Runtime.Configuration
  nameWithType: Orleans.GpuBridge.Runtime.Configuration
  fullName: Orleans.GpuBridge.Runtime.Configuration
  type: Namespace
  assemblies:
  - Orleans.GpuBridge.Runtime
references:
- uid: Orleans.GpuBridge.Runtime.Configuration.ProviderSelectionOptions
  commentId: T:Orleans.GpuBridge.Runtime.Configuration.ProviderSelectionOptions
  href: Orleans.GpuBridge.Runtime.Configuration.ProviderSelectionOptions.html
  name: ProviderSelectionOptions
  nameWithType: ProviderSelectionOptions
  fullName: Orleans.GpuBridge.Runtime.Configuration.ProviderSelectionOptions
- uid: Orleans.GpuBridge.Runtime.Configuration.RequiredCapabilities
  commentId: T:Orleans.GpuBridge.Runtime.Configuration.RequiredCapabilities
  parent: Orleans.GpuBridge.Runtime.Configuration
  href: Orleans.GpuBridge.Runtime.Configuration.RequiredCapabilities.html
  name: RequiredCapabilities
  nameWithType: RequiredCapabilities
  fullName: Orleans.GpuBridge.Runtime.Configuration.RequiredCapabilities
- uid: Orleans.GpuBridge.Runtime.Configuration
  commentId: N:Orleans.GpuBridge.Runtime.Configuration
  href: Orleans.html
  name: Orleans.GpuBridge.Runtime.Configuration
  nameWithType: Orleans.GpuBridge.Runtime.Configuration
  fullName: Orleans.GpuBridge.Runtime.Configuration
  spec.csharp:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.Runtime
    name: Runtime
    href: Orleans.GpuBridge.Runtime.html
  - name: .
  - uid: Orleans.GpuBridge.Runtime.Configuration
    name: Configuration
    href: Orleans.GpuBridge.Runtime.Configuration.html
  spec.vb:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.Runtime
    name: Runtime
    href: Orleans.GpuBridge.Runtime.html
  - name: .
  - uid: Orleans.GpuBridge.Runtime.Configuration
    name: Configuration
    href: Orleans.GpuBridge.Runtime.Configuration.html
