### YamlMime:ManagedReference
items:
- uid: Orleans.GpuBridge.Diagnostics.Configuration
  commentId: N:Orleans.GpuBridge.Diagnostics.Configuration
  id: Orleans.GpuBridge.Diagnostics.Configuration
  children:
  - Orleans.GpuBridge.Diagnostics.Configuration.GpuMetricsOptions
  langs:
  - csharp
  - vb
  name: Orleans.GpuBridge.Diagnostics.Configuration
  nameWithType: Orleans.GpuBridge.Diagnostics.Configuration
  fullName: Orleans.GpuBridge.Diagnostics.Configuration
  type: Namespace
  assemblies:
  - Orleans.GpuBridge.Diagnostics
references:
- uid: Orleans.GpuBridge.Diagnostics.Configuration.GpuMetricsOptions
  commentId: T:Orleans.GpuBridge.Diagnostics.Configuration.GpuMetricsOptions
  href: Orleans.GpuBridge.Diagnostics.Configuration.GpuMetricsOptions.html
  name: GpuMetricsOptions
  nameWithType: GpuMetricsOptions
  fullName: Orleans.GpuBridge.Diagnostics.Configuration.GpuMetricsOptions
