### YamlMime:ManagedReference
items:
- uid: Orleans.GpuBridge.Logging.Configuration
  commentId: N:Orleans.GpuBridge.Logging.Configuration
  id: Orleans.GpuBridge.Logging.Configuration
  children:
  - Orleans.GpuBridge.Logging.Configuration.BufferConfiguration
  - Orleans.GpuBridge.Logging.Configuration.ConsoleConfiguration
  - Orleans.GpuBridge.Logging.Configuration.DelegateManagerConfiguration
  - Orleans.GpuBridge.Logging.Configuration.FileConfiguration
  - Orleans.GpuBridge.Logging.Configuration.GpuBridgeLoggingOptions
  - Orleans.GpuBridge.Logging.Configuration.LoggingConfigurationExtensions
  - Orleans.GpuBridge.Logging.Configuration.TelemetryConfiguration
  - Orleans.GpuBridge.Logging.Configuration.ValidationResult
  langs:
  - csharp
  - vb
  name: Orleans.GpuBridge.Logging.Configuration
  nameWithType: Orleans.GpuBridge.Logging.Configuration
  fullName: Orleans.GpuBridge.Logging.Configuration
  type: Namespace
  assemblies:
  - Orleans.GpuBridge.Logging
references:
- uid: Orleans.GpuBridge.Logging.Configuration.BufferConfiguration
  commentId: T:Orleans.GpuBridge.Logging.Configuration.BufferConfiguration
  parent: Orleans.GpuBridge.Logging.Configuration
  href: Orleans.GpuBridge.Logging.Configuration.BufferConfiguration.html
  name: BufferConfiguration
  nameWithType: BufferConfiguration
  fullName: Orleans.GpuBridge.Logging.Configuration.BufferConfiguration
- uid: Orleans.GpuBridge.Logging.Configuration.ConsoleConfiguration
  commentId: T:Orleans.GpuBridge.Logging.Configuration.ConsoleConfiguration
  parent: Orleans.GpuBridge.Logging.Configuration
  href: Orleans.GpuBridge.Logging.Configuration.ConsoleConfiguration.html
  name: ConsoleConfiguration
  nameWithType: ConsoleConfiguration
  fullName: Orleans.GpuBridge.Logging.Configuration.ConsoleConfiguration
- uid: Orleans.GpuBridge.Logging.Configuration.DelegateManagerConfiguration
  commentId: T:Orleans.GpuBridge.Logging.Configuration.DelegateManagerConfiguration
  parent: Orleans.GpuBridge.Logging.Configuration
  href: Orleans.GpuBridge.Logging.Configuration.DelegateManagerConfiguration.html
  name: DelegateManagerConfiguration
  nameWithType: DelegateManagerConfiguration
  fullName: Orleans.GpuBridge.Logging.Configuration.DelegateManagerConfiguration
- uid: Orleans.GpuBridge.Logging.Configuration.FileConfiguration
  commentId: T:Orleans.GpuBridge.Logging.Configuration.FileConfiguration
  parent: Orleans.GpuBridge.Logging.Configuration
  href: Orleans.GpuBridge.Logging.Configuration.FileConfiguration.html
  name: FileConfiguration
  nameWithType: FileConfiguration
  fullName: Orleans.GpuBridge.Logging.Configuration.FileConfiguration
- uid: Orleans.GpuBridge.Logging.Configuration.GpuBridgeLoggingOptions
  commentId: T:Orleans.GpuBridge.Logging.Configuration.GpuBridgeLoggingOptions
  parent: Orleans.GpuBridge.Logging.Configuration
  href: Orleans.GpuBridge.Logging.Configuration.GpuBridgeLoggingOptions.html
  name: GpuBridgeLoggingOptions
  nameWithType: GpuBridgeLoggingOptions
  fullName: Orleans.GpuBridge.Logging.Configuration.GpuBridgeLoggingOptions
- uid: Orleans.GpuBridge.Logging.Configuration.LoggingConfigurationExtensions
  commentId: T:Orleans.GpuBridge.Logging.Configuration.LoggingConfigurationExtensions
  parent: Orleans.GpuBridge.Logging.Configuration
  href: Orleans.GpuBridge.Logging.Configuration.LoggingConfigurationExtensions.html
  name: LoggingConfigurationExtensions
  nameWithType: LoggingConfigurationExtensions
  fullName: Orleans.GpuBridge.Logging.Configuration.LoggingConfigurationExtensions
- uid: Orleans.GpuBridge.Logging.Configuration.TelemetryConfiguration
  commentId: T:Orleans.GpuBridge.Logging.Configuration.TelemetryConfiguration
  parent: Orleans.GpuBridge.Logging.Configuration
  href: Orleans.GpuBridge.Logging.Configuration.TelemetryConfiguration.html
  name: TelemetryConfiguration
  nameWithType: TelemetryConfiguration
  fullName: Orleans.GpuBridge.Logging.Configuration.TelemetryConfiguration
- uid: Orleans.GpuBridge.Logging.Configuration.ValidationResult
  commentId: T:Orleans.GpuBridge.Logging.Configuration.ValidationResult
  parent: Orleans.GpuBridge.Logging.Configuration
  href: Orleans.GpuBridge.Logging.Configuration.ValidationResult.html
  name: ValidationResult
  nameWithType: ValidationResult
  fullName: Orleans.GpuBridge.Logging.Configuration.ValidationResult
- uid: Orleans.GpuBridge.Logging.Configuration
  commentId: N:Orleans.GpuBridge.Logging.Configuration
  href: Orleans.html
  name: Orleans.GpuBridge.Logging.Configuration
  nameWithType: Orleans.GpuBridge.Logging.Configuration
  fullName: Orleans.GpuBridge.Logging.Configuration
  spec.csharp:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.Logging
    name: Logging
    href: Orleans.GpuBridge.Logging.html
  - name: .
  - uid: Orleans.GpuBridge.Logging.Configuration
    name: Configuration
    href: Orleans.GpuBridge.Logging.Configuration.html
  spec.vb:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.Logging
    name: Logging
    href: Orleans.GpuBridge.Logging.html
  - name: .
  - uid: Orleans.GpuBridge.Logging.Configuration
    name: Configuration
    href: Orleans.GpuBridge.Logging.Configuration.html
