### YamlMime:ManagedReference
items:
- uid: Orleans.GpuBridge.HealthChecks.Configuration
  commentId: N:Orleans.GpuBridge.HealthChecks.Configuration
  id: Orleans.GpuBridge.HealthChecks.Configuration
  children:
  - Orleans.GpuBridge.HealthChecks.Configuration.GpuHealthCheckOptions
  langs:
  - csharp
  - vb
  name: Orleans.GpuBridge.HealthChecks.Configuration
  nameWithType: Orleans.GpuBridge.HealthChecks.Configuration
  fullName: Orleans.GpuBridge.HealthChecks.Configuration
  type: Namespace
  assemblies:
  - Orleans.GpuBridge.HealthChecks
references:
- uid: Orleans.GpuBridge.HealthChecks.Configuration.GpuHealthCheckOptions
  commentId: T:Orleans.GpuBridge.HealthChecks.Configuration.GpuHealthCheckOptions
  parent: Orleans.GpuBridge.HealthChecks.Configuration
  href: Orleans.GpuBridge.HealthChecks.Configuration.GpuHealthCheckOptions.html
  name: GpuHealthCheckOptions
  nameWithType: GpuHealthCheckOptions
  fullName: Orleans.GpuBridge.HealthChecks.Configuration.GpuHealthCheckOptions
- uid: Orleans.GpuBridge.HealthChecks.Configuration
  commentId: N:Orleans.GpuBridge.HealthChecks.Configuration
  href: Orleans.html
  name: Orleans.GpuBridge.HealthChecks.Configuration
  nameWithType: Orleans.GpuBridge.HealthChecks.Configuration
  fullName: Orleans.GpuBridge.HealthChecks.Configuration
  spec.csharp:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.HealthChecks
    name: HealthChecks
    href: Orleans.GpuBridge.HealthChecks.html
  - name: .
  - uid: Orleans.GpuBridge.HealthChecks.Configuration
    name: Configuration
    href: Orleans.GpuBridge.HealthChecks.Configuration.html
  spec.vb:
  - uid: Orleans
    name: Orleans
    href: Orleans.html
  - name: .
  - uid: Orleans.GpuBridge
    name: GpuBridge
    href: Orleans.GpuBridge.html
  - name: .
  - uid: Orleans.GpuBridge.HealthChecks
    name: HealthChecks
    href: Orleans.GpuBridge.HealthChecks.html
  - name: .
  - uid: Orleans.GpuBridge.HealthChecks.Configuration
    name: Configuration
    href: Orleans.GpuBridge.HealthChecks.Configuration.html
